# Generated by Django 4.2 on 2023-05-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='max_no_members',
            field=models.PositiveIntegerField(default=255000),
        ),
    ]
