# Generated by Django 4.2 on 2023-05-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_max_no_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.ImageField(upload_to=''),
        ),
    ]
